import 'package:flutter/material.dart';
import 'package:sendotp_flutter_sdk/sendotp_flutter_sdk.dart';
import 'services/onesignal_service.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'firebase_options.dart';

import 'app_colors.dart';
import 'app_state.dart';
import 'notification_service.dart';
import 'splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the config generated by `flutterfire configure`.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Register background/terminated handler for incoming FCM messages.
  // (Defined as a top-level function inside notification_service.dart —
  // must be registered before runApp, same as before.)
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  // Everything else — local notification channel setup, asking for the
  // OS Allow/Block permission popup, saving the FCM token to the backend,
  // and the foreground push listener — now lives in ONE place:
  // NotificationService. main.dart no longer duplicates any of that.
    await NotificationService.instance.init();

    // Restore saved login (userId) so it survives app restarts —
  // needed for product details page to fetch the saved delivery address.
  await AppState.instance.loadSavedLogin();

  OneSignalService.instance.initialize('e2ba850f-0954-4c0a-8360-c17abbff7acf');
  OneSignalService.instance.setRoleTag('customer');

  // Initialize MSG91 OTP Widget — must happen before runApp,
  // so it's ready when the login screen calls sendOTP/verifyOTP.
  OTPWidget.initializeWidget(
    '3669786e7435383131343834',      // widgetId
    '573884T1J68w0qcnh6ab541bcP1',   // authToken
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sumathi\'s Styles',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: AppColors.primary,
        colorScheme: ColorScheme.fromSeed(seedColor: AppColors.primary),
        useMaterial3: true,
      ),
            home: const SplashScreen(),
    );
  }
}